source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘UnsplashDemo’ do
	
	# 网络请求
	pod 'Alamofire', '4.8.1'
	# 图片加载
	pod 'Kingfisher', '4.10.1'
	# 自动布局
	pod 'SnapKit', '4.2.0'
	# 字典转模型
	pod 'ObjectMapper', '3.4.2'
	# JSON解析库
	pod 'SwiftyJSON', '4.2.0'
	# MJ刷新
	pod 'MJRefresh', '3.1.15.7'
	# 吐司提示
	pod 'MBProgressHUD', '~> 1.1.0'
	

end
